### ISSUE TITLE
Footer hidden by map

### ISSUE THREAD

**Issue by pdonias** [SimpleProgrammingAU/whatismyradius#2]
The map element hides the footer when the page is scrolled all the way up:
![Capture_2020-08-13_16:03:44](https://user-images.githubusercontent.com/10992860/90144462-22a44f00-dd7f-11ea-83e0-f1863089554a.png)

**Comment by SimpleProgrammingAU** [comment]
Have added the z-index property to the footer to address the issue.

**Comment by SimpleProgrammingAU** [comment]
I'll add that I needed to clear the browser cache before the update would be applied.
